# Generated by Django 5.2 on 2025-04-29 04:58

import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('watchlist', djongo.models.fields.JSONField(blank=True, default=list)),
                ('genre', djongo.models.fields.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
